import { Roboto } from "next/font/google";
import "./globals.css";
import Hero from "@/components/layout/Hero.js";
import Header from "@/components/layout/Header";

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <Header/>
          {children}
          <footer className="border-t p-8 text-center text-gray-900 mt-16">
            &copy; 2024, Todos os Direitos Reservados. ®
          </footer>
        </main>  
        
      </body>
    </html>
  );
}
